cms/urls.py
# coding=utf-8

# hier definiëren we alle URLs die beginnen met bedrijf (dit komt na login later)

from django.conf.urls import url
from . import views
from cms import views as cms_views

urlpatterns = [
    #voorbeeld: /
    url(r'^$', cms_views.index, name='index'),
    # voorbeeld: /schaap/internnr123

    # MOET NOG VERDER UITGEWERKT WORDEN!!!!


]

mijnkuddeproject/urls.py
# coding=utf-8

"""mijnkuddeproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.contrib import admin
from schapen import views as schapen_views
from django.contrib.auth import views as auth_views

urlpatterns = [

    url(r'^bedrijf/', include('schapen.urls', namespace='schapen')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name = 'login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'registration/logged_out.html'}, name = 'logout'),
    url(r'^$', include('cms.urls', namespace='cms')),

]

schapen/urls.py
# coding=utf-8

# hier definiëren we alle URLs die beginnen met bedrijf (dit komt na login later)

from django.conf.urls import url
from . import views
from schapen import views as schapen_views

app_name = 'schapen'

urlpatterns = [
    #voorbeeld: /

    # voorbeeld: /schaap/internnr123
    url(r'^aanwezige_schapen', schapen_views.bedrijf_aanwezige_schapen, name = 'bedrijf_aanwezige_schapen'),
    url(r'^alle_schapen', schapen_views.bedrijf_alle_schapen, name = 'bedrijf_alle_schapen'),
    url(r'^schaap_toevoegen', schapen_views.bedrijf_schaap_toevoegen, name = 'bedrijf_schaap_toevoegen'),
    url(r'^schaap/(?P<id>[0-9]+)/$', schapen_views.bedrijf_schaap_detail, name = 'bedrijf_schaap_detail'),
    url(r'^$', schapen_views.bedrijf_index, name='bedrijf_index'),


]

cms/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

schapen/models.py
# coding=utf-8

from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.db.models import Q
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from schapen.middleware.global_request import get_request


class SchapenManager(models.Manager):
    def get_queryset(self):
        request = get_request()
        if request:
            print(request.user)
        if request is not None and not request.user.is_superuser:
            return super(SchapenManager, self)\
                .get_queryset().filter(owner=request.user)
        return super(SchapenManager, self).get_queryset()


class Schapen(models.Model):
    geslacht_keuzes = ((1, 'Ram'), (2, 'Ooi'))
    objects = SchapenManager()

    intern_nummer = models.CharField(max_length=50)
    geslacht = models.IntegerField(choices=geslacht_keuzes)
    geboortedatum = models.DateField(null=True, blank=True)
    einddatum = models.DateField(null=True, blank=True)
    Sanitel = models.CharField(max_length=11)
    moeder = models.ForeignKey('Schapen', models.SET_NULL, null=True,
        related_name='moeders',
        blank=True,
        #limit_choices_to={'geslacht': 2}
    )
    vader = models.ForeignKey('Schapen', models.SET_NULL, null=True,
        related_name='vaders',
        blank=True,
        #limit_choices_to={'geslacht': 1}
    )
    owner = models.ForeignKey(User, default=1, null=True)
    pub_datum = models.DateField(null=True, blank=True)

    def __str__(self):
        return '%s %s' % (self.__class__.__name__, self.intern_nummer)

schapen/forms.py
from django import forms
from django.forms import extras
from .models import Schapen
from django.forms.fields import DateField
from django.db.models import Q
from django.contrib.auth.models import User

from .middleware.global_request import get_request


class AddSchapen(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AddSchapen, self).__init__( *args, **kwargs)
        user = get_request().user
        self.fields['moeder'].queryset = Schapen.objects.filter(owner=user, geslacht=2)
        self.fields['vader'].queryset = Schapen.objects.filter(owner=user, geslacht=1)

    class Meta:
        model = Schapen
        exclude = ('owner','pub_datum')

cms/views.py
from django.shortcuts import render

# Create your views here.

# aan te passen from cms.models import Schapen
from django.http import HttpResponse

# view voor basis pagina website, login vetrekt van hier
def index(request):
    return render(request, 'cms/index.html')

schapen/views.py
from django.shortcuts import render


# Create your views here.

from schapen.models import Schapen
from schapen.forms import AddSchapen
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse



# view na login, alles met suffix bedrijf
@login_required
def bedrijf_index(request):
    today = datetime.datetime.today()
    huidige_gebruiker = request.user
    schapen_overzicht = Schapen.objects.filter(Q(einddatum__gt = today) | Q(einddatum__isnull = True )).order_by('intern_nummer')
    schapen_overzicht_pergebruiker = schapen_overzicht.filter(owner = huidige_gebruiker )
    context = {'schapen_overzicht':schapen_overzicht_pergebruiker}
    return render(request, 'bedrijf/index.html', context)

@login_required
def bedrijf_aanwezige_schapen(request):
    today = datetime.datetime.today()
    huidige_gebruiker = request.user
    schapen_overzicht = Schapen.objects.filter(Q(einddatum__gt = today) | Q(einddatum__isnull = True )).order_by('intern_nummer')
    schapen_overzicht_pergebruiker = schapen_overzicht.filter(owner = huidige_gebruiker )
    context = {'schapen_overzicht':schapen_overzicht_pergebruiker}
    return render(request, 'bedrijf/aanwezige_schapen.html', context)

@login_required
def bedrijf_alle_schapen(request):
    huidige_gebruiker = request.user
    schapen_overzicht = Schapen.objects.order_by('intern_nummer')
    schapen_overzicht_pergebruiker = schapen_overzicht.filter(owner = huidige_gebruiker )
    context = {'schapen_overzicht':schapen_overzicht_pergebruiker}
    return render(request, 'bedrijf/alle_schapen.html', context)

@login_required
def bedrijf_schaap_toevoegen(request):
    if request.method == "POST":
        form = AddSchapen(request.POST)
        if form.is_valid():
            formulier = form.save(commit=False)
            formulier.owner = request.user
            formulier.pub_datum = datetime.datetime.now()
            formulier.save()
            #schapen_overzicht = Schapen.objects.order_by('intern_nummer')
            #context = {'schapen_overzicht':schapen_overzicht}
            #return render(request, 'bedrijf/alle_schapen.html', context)
            #return HttpResponseRedirect(reverse('schapen:bedrijf_schaap_toevoegen'))
    else:
        form = AddSchapen()
    return render(request, 'bedrijf/schaap_toevoegen.html',  {'form': form})

@login_required
def bedrijf_schaap_detail(request, id):
    schaap = get_object_or_404(Schapen, pk=id)
    form = AddSchapen()
    return render(request, 'bedrijf/schaap_detail.html', {'schapen': schaap, 'form': form})

cms/templates/cms/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

    <title>Mijn Kudde.be - Welkom</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/mijnkudde.css' %}"
</head>

<body>
    <div id="sidebar">

        <ul>
            <li><a href="/">Startpagina</a></li>

        </ul>
      
    </div>

    <div id="content">
      <p>Dit is de startpagina</p>
      <p>Hier komt login en dergelijke</p>
    </div>
</body>
</html>

schapen/templates/bedrijf/aanwezige_schapen.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Lijst van de aanwezige schapen{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-9"><h1>Aanwezige schapen</h1></div>
<div class="col-sm3"><a href="{% url 'schapen:bedrijf_schaap_toevoegen' %}" class="btn btn-primary btn-lg knop_titel"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Schaap toevoegen</a></div>
</div>


{% if schapen_overzicht %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Intern nummer</th>
        <th>Geboortedatum</th>
        <th>Geslacht</th>
      </tr>
    </thead>
    <tbody>
    {% for beest in schapen_overzicht %}
      <tr>
        <td><a href="{% url 'schapen:bedrijf_schaap_detail' beest.id %}">{{beest.intern_nummer}}</a></td>
        <td>{{beest.geboortedatum}}</td>
        <td>{{beest.get_geslacht_display}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
  <p>Geen schapen te vinden!!</p>
{% endif %}

{% endblock %}

schapen/templates/bedrijf/alle_schapen.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Lijst van alle schapen{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-9"><h1>Alle schapen</h1></div>
<div class="col-sm3"></div>
</div>
{% if schapen_overzicht %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Intern nummer</th>
        <th>Geboortedatum</th>
        <th>Geslacht</th>
      </tr>
    </thead>
    <tbody>
    {% for beest in schapen_overzicht %}
      <tr>
        <td>{{beest.intern_nummer}}</td>
        <td>{{beest.geboortedatum}}</td>
        <td>{{beest.get_geslacht_display}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
  <p>Geen schapen te vinden!!</p>
{% endif %}



{% endblock %}

schapen/templates/bedrijf/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="nl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>{% block title %}Mijn Kudde.be{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.css' %}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/mijnkudde.css' %}">
    <!-- link naar glyphicons online -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-dark navbar-fixed-top bg-success">
  <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation"></button>
    <a class="navbar-brand" href="{% url 'schapen:bedrijf_index' %}">MijnBedrijf</a>
    <div id="navbar">
      <nav class="nav navbar-nav float-xs-right">
        <a class="nav-item nav-link" href="#">Profile</a>
        <a class="nav-item nav-link" href="{% url 'logout' %}">Uitloggen</a>
      </nav>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">

      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
          <li><a href="#">Overzicht</a></li>
          <li><a href="{% url 'schapen:bedrijf_alle_schapen' %}">Schapen</a></li>
          <li>
            <ul>
              <li><a href="{% url 'schapen:bedrijf_aanwezige_schapen' %}">Aanwezige schapen</a></li>
              <li><a href="{% url 'schapen:bedrijf_alle_schapen' %}">Alle schapen</a></li>
            </ul>
            </li>
        </ul>

      </div>

      <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">

        {% block content %}


        {% endblock %}
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="{% static 'docs/assets/js/vendor/jquery.min.js' %}"><\/script>')</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
  <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>


</body>
</html>

schapen/templates/bedrijf/index.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Welkom{% endblock %}

{% block content %}
<h1>Lijst van aanwezig schapen</h1>

{% if schapen_overzicht %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Intern nummer</th>
        <th>Geboortedatum</th>
        <th>Geslacht</th>
      </tr>
    </thead>
    <tbody>
    {% for beest in schapen_overzicht %}
      <tr>
        <td>{{beest.intern_nummer}}</td>
        <td>{{beest.geboortedatum}}</td>
        <td>{{beest.geslacht}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
  <p>Geen schapen te vinden!!</p>
{% endif %}

{% endblock %}

schapen/templates/bedrijf/index0.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Een nieuw schaap toevoegen{% endblock %}



{% block content %}
<h1>Een nieuw schaap toevoegen</h1>


<form action="{% url 'reviews:add_review' wine.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>


{% endblock %}

schapen/templates/bedrijf/schaap_detail.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Detail van schaap {{ schapen.intern_nummer }}{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-9"><h1>Detail van schaap {{ schapen.intern_nummer }}</h1></div>
<div class="col-sm3"></div>
</div>
{{ schapen.intern_nummer }}

{{ schapen.geslacht }}

{% endblock %}

schapen/templates/bedrijf/schaap_toevoegen.html
{% extends "bedrijf/base.html" %}

{% block title %}Mijn Kudde.be - Een nieuw schaap toevoegen{% endblock %}



{% block content %}
<h1>Een nieuw schaap toevoegen</h1>

{% if error_message %}
<div class="alert alert-warning" role="alert">
{{error_message}}
</div>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Toevoegen" />
</form>


{% endblock %}